const bottles = [
  {
    bottleTitle: 'Hangar 1',
    bottleSubTitle: 'Straight Vodka',
    bottleFullTitle: 'Hangar 1 Straight Vodka',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Hangar 1',
    bottleShortMaker: 'hangar1',
    bottleStock: 10,
    bottleShortName: 'hangar1-straightvodka',
    bottleImg: '/static/bottles/low-res/Hangar1-straight.png',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'All Purpose Vodka',
    bottleFullTitle: 'St. George All Purpose Vodka',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-allpurpose',
    bottleImg: '/static/bottles/low-res/StGeorge-all-purpose.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'Single Malt Whiskey',
    bottleFullTitle: 'St. George Single Malt Whiskey',
    bottlePrice: '39.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-singlemaltwhiskey',
    bottleImg: '/static/bottles/low-res/StGeorge-whiskey.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'California Citrus',
    bottleFullTitle: 'St. George California Citrus',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-cc',
    bottleImg: '/static/bottles/low-res/StGeorge_cacitrus.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'Green Chile',
    bottleFullTitle: 'St. George Green Chile',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-green-chile',
    bottleImg: '/static/bottles/low-res/StGeorge_grnchile.jpg',
  },
  {
    bottleTitle: 'Bulliet',
    bottleSubTitle: 'Frontier Whiskey',
    bottleFullTitle: 'Bulliet Bourbon Frontier Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Bulliet Bourbon',
    bottleShortMaker: 'bulliet',
    bottleStock: 10,
    bottleShortName: 'bulliet-whiskey',
    bottleImg: '/static/bottles/low-res/Bulliet.jpg',
  },
  {
    bottleTitle: 'Bulliet',
    bottleSubTitle: 'Rye Whiskey',
    bottleFullTitle: 'Bulliet Bourbon Rye Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Bulliet Bourbon',
    bottleShortMaker: 'bulliet',
    bottleStock: 10,
    bottleShortName: 'bulliet-rye-whiskey',
    bottleImg: '/static/bottles/low-res/BullietRye.jpg',
  },
  {
    bottleTitle: 'Evan Williams',
    bottleSubTitle: 'Straight Bourbon Whiskey',
    bottleFullTitle: 'Evan Williams Straight Bourbon Whiskey',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Evan Williams',
    bottleShortMaker: 'evanwilliams',
    bottleStock: 10,
    bottleShortName: 'evanwilliams-straight-whiskey',
    bottleImg: '/static/bottles/low-res/EvanWilliams.jpg',
  },
  {
    bottleTitle: 'Fireball',
    bottleSubTitle: 'Cinnamon Whiskey',
    bottleFullTitle: 'Fireball Cinnamon Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Fireball',
    bottleShortMaker: 'fireball',
    bottleStock: 10,
    bottleShortName: 'fireball-cinnamon-whiskey',
    bottleImg: '/static/bottles/low-res/Fireball.jpg',
  },
  {
    bottleTitle: 'Iwai',
    bottleSubTitle: 'Mars Whiskey',
    bottleFullTitle: 'Iwai Mars Whiskey',
    bottlePrice: '109.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Iwai',
    bottleShortMaker: 'iwai',
    bottleStock: 10,
    bottleShortName: 'iwai-mars-whiskey',
    bottleImg: '/static/bottles/low-res/Iwai.jpg',
  },
  {
    bottleTitle: 'Iwai',
    bottleSubTitle: 'Tradition Whiskey',
    bottleFullTitle: 'Iwai Tradition Whiskey',
    bottlePrice: '109.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Iwai',
    bottleShortMaker: 'iwai',
    bottleStock: 10,
    bottleShortName: 'iwai-tradition-whiskey',
    bottleImg: '/static/bottles/low-res/Iwai_tradition.jpg',
  },
  {
    bottleTitle: 'Jameson',
    bottleSubTitle: 'Irish Whiskey',
    bottleFullTitle: 'Jameson Irish Whiskey',
    bottlePrice: '36.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Jameson',
    bottleShortMaker: 'jameson',
    bottleStock: 10,
    bottleShortName: 'jameson-irish-whiskey',
    bottleImg: '/static/bottles/low-res/Jameson_15.jpg',
  },
  {
    bottleTitle: 'Jameson',
    bottleSubTitle: 'Irish Whiskey',
    bottleFullTitle: 'Jameson Irish Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Jameson',
    bottleShortMaker: 'jameson',
    bottleStock: 10,
    bottleShortName: 'jameson-irish-whiskey',
    bottleImg: '/static/bottles/low-res/Jameson_750ml.jpg',
  },
  {
    bottleTitle: 'Centenario',
    bottleSubTitle: 'Anejo',
    bottleFullTitle: 'Centenario Anejo',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Centenario',
    bottleShortMaker: 'centenario',
    bottleStock: 10,
    bottleShortName: 'centenario-anejo',
    bottleImg: '/static/bottles/low-res/Centario.jpg',
  },
  {
    bottleTitle: 'Suerte',
    bottleSubTitle: 'Blanco',
    bottleFullTitle: 'Suerte Blanco',
    bottlePrice: '22.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Suerte',
    bottleShortMaker: 'suerte',
    bottleStock: 10,
    bottleShortName: 'suerte-blanco',
    bottleImg: '/static/bottles/low-res/Suerte.jpg',
  },
  {
    bottleTitle: 'Nuestra Soledad',
    bottleSubTitle: 'Mezcal',
    bottleFullTitle: 'Nuestra Soledad Mezcal',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Nuestra Soledad',
    bottleShortMaker: 'nuestra-soledad',
    bottleStock: 10,
    bottleShortName: 'nuestra-soledad-mezcal',
    bottleImg: '/static/bottles/low-res/Nuestra_soledad.jpg',
  },
  {
    bottleTitle: 'Effen',
    bottleSubTitle: 'Vodka',
    bottleFullTitle: 'Effen Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Effen',
    bottleShortMaker: 'effen',
    bottleStock: 10,
    bottleShortName: 'effen-vodka',
    bottleImg: '/static/bottles/low-res/Effen_clr.jpg',
  },
  {
    bottleTitle: 'Skyy',
    bottleSubTitle: 'Vodka',
    bottleFullTitle: 'Skyy Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Skyy',
    bottleShortMaker: 'skyy',
    bottleStock: 10,
    bottleShortName: 'skyy-vodka',
    bottleImg: '/static/bottles/low-res/Skyy.jpg',
  },
  {
    bottleTitle: 'Tito\'s',
    bottleSubTitle: 'Handmade Vodka',
    bottleFullTitle: 'Tito\'s Handmade Vodka',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Tito\'s',
    bottleShortMaker: 'titos',
    bottleStock: 10,
    bottleShortName: 'titos-handmade-vodka',
    bottleImg: '/static/bottles/low-res/Titos.jpg',
  },
  {
    bottleTitle: 'Effen',
    bottleSubTitle: 'Cucumber Vodka',
    bottleFullTitle: 'Effen Cucumber Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Effen',
    bottleShortMaker: 'effen',
    bottleStock: 10,
    bottleShortName: 'effen-cucumber-vodka',
    bottleImg: '/static/bottles/low-res/Effen_grn.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Blanc',
    bottleFullTitle: 'Dolin Vermouth Blanc',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-blanc',
    bottleImg: '/static/bottles/low-res/Dolin-vermouth-blanc.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Rouge',
    bottleFullTitle: 'Dolin Vermouth Rouge',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-rouge',
    bottleImg: '/static/bottles/low-res/Dolin-rouge.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Dry',
    bottleFullTitle: 'Dolin Vermouth Dry',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-dry',
    bottleImg: '/static/bottles/low-res/Dolin_vermouthdry.jpg',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Dry Vermouth',
    bottleFullTitle: 'Lo-fi Dry Vermouth',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-dry-vermouth',
    bottleImg: '/static/bottles/low-res/Lofi-dry-vermouth.jpg',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Gentian Amaro',
    bottleFullTitle: 'Lo-fi Gentian Amaro',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-gentian-amaro',
    bottleImg: '/static/bottles/low-res/Lofi-gentian-amaro.png',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Sweet Vermouth',
    bottleFullTitle: 'Lo-fi Sweet Vermouth',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-sweet-vermouth',
    bottleImg: '/static/bottles/low-res/Lofi-sweet-vermouth.jpg',
  },
  {
    bottleTitle: 'Moet & Chandon',
    bottleSubTitle: 'Nectar Imperial',
    bottleFullTitle: 'Moet & Chandon Nectar Imperial',
    bottlePrice: '69.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'champagne',
    bottleMaker: 'Moet & Chandon',
    bottleShortMaker: 'moet-chandon',
    bottleStock: 10,
    bottleShortName: 'moet-chandon-nectar-imperial',
    bottleImg: '/static/bottles/low-res/MC_nectarimperial.jpg',
  },
  {
    bottleTitle: 'Perrier Jouet',
    bottleSubTitle: 'Blanc',
    bottleFullTitle: 'Perrier Joet Blanc',
    bottlePrice: '399.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'champagne',
    bottleMaker: 'Perrier Jouet',
    bottleShortMaker: 'perrier-jouet',
    bottleStock: 10,
    bottleShortName: 'perrier-jouet-blanc',
    bottleImg: '/static/bottles/low-res/PJ_blanc.jpg',
  },
  {
    bottleTitle: 'Fever-Tree',
    bottleSubTitle: 'Club Soda',
    bottleFullTitle: 'Fever-Tree Club Soda',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Fever-Tree',
    bottleShortMaker: 'fevertree',
    bottleStock: 10,
    bottleShortName: 'fevertree-clubsoda',
    bottleImg: '/static/bottles/low-res/FT_Clubsoda.jpg',
  },
  {
    bottleTitle: 'Fever-Tree',
    bottleSubTitle: 'Tonic Water',
    bottleFullTitle: 'Fever-Tree Tonic Water',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Fever-Tree',
    bottleShortMaker: 'fevertree',
    bottleStock: 10,
    bottleShortName: 'fevertree-tonicwater',
    bottleImg: '/static/bottles/low-res/FT_Tonicwater.jpg',
  },
  {
    bottleTitle: 'Martinelli\'s',
    bottleSubTitle: 'Apple Juice',
    bottleFullTitle: 'Martinelli\'s Apple Juice',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Martinelli\'s',
    bottleShortMaker: 'martinellis',
    bottleStock: 10,
    bottleShortName: 'martinellis-applejuice',
    bottleImg: '/static/bottles/low-res/Martin_Apple.jpg',
  },
  {
    bottleTitle: 'Bundaberg',
    bottleSubTitle: 'Pink Grapefruit',
    bottleFullTitle: 'Bundaberg Pink Grapefruit',
    bottlePrice: '6.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Bundaberg',
    bottleShortMaker: 'bundaberg',
    bottleStock: 10,
    bottleShortName: 'bundaberg-pinkgrapefruit-pck',
    bottleImg: '/static/bottles/low-res/Bundaberg.jpg',
  },
  {
    bottleTitle: 'Canada Dry',
    bottleSubTitle: 'Mandarin Orange',
    bottleFullTitle: 'Canada Dry Mandarin Orange',
    bottlePrice: '2.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Canada Dry',
    bottleShortMaker: 'canadadry',
    bottleStock: 10,
    bottleShortName: 'canadadry-mandarinorange',
    bottleImg: '/static/bottles/low-res/CD_Mandarinsprk.jpg',
  },
  {
    bottleTitle: 'Canada Dry',
    bottleSubTitle: 'Raspberry',
    bottleFullTitle: 'Canada Dry Raspberry',
    bottlePrice: '2.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Canada Dry',
    bottleShortMaker: 'canadadry',
    bottleStock: 10,
    bottleShortName: 'canadadry-raspberry',
    bottleImg: '/static/bottles/low-res/CD_Raspberrysprk.jpg',
  },
  {
    bottleTitle: 'Clandestine',
    bottleSubTitle: 'Absinthe',
    bottleFullTitle: 'Clandestine Absinthe',
    bottlePrice: '69.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'absinthe',
    bottleMaker: 'Clandestine',
    bottleShortMaker: 'clandestine',
    bottleStock: 10,
    bottleShortName: 'clandestine-absinthe',
    bottleImg: '/static/bottles/low-res/Clandestine_absinthe.jpg',
  },
  {
    bottleTitle: 'Fernet Branca',
    bottleSubTitle: 'Liqueur',
    bottleFullTitle: 'Fernet Branca Liqueur',
    bottlePrice: '34.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'liqueur',
    bottleMaker: 'Fernet Branca',
    bottleShortMaker: 'fernet-branca',
    bottleStock: 10,
    bottleShortName: 'fernet-branca-liqueur',
    bottleImg: '/static/bottles/low-res/Fernet_branca.jpg',
  },
  {
    bottleTitle: 'Masters of Mixers',
    bottleSubTitle: 'Unsweeted Lemon Juice',
    bottleFullTitle: 'Masters of Mixers Unsweeted Lemon Juice',
    bottlePrice: '4.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'mixers',
    bottleMaker: 'Masters of Mixers',
    bottleShortMaker: 'masters-mixers',
    bottleStock: 10,
    bottleShortName: 'masters-mixers-unsweeted-lemon-juice',
    bottleImg: '/static/bottles/low-res/MM_Lemonjuice.jpg',
  },
  {
    bottleTitle: 'Kirin Ichiban',
    bottleSubTitle: '100% Malt',
    bottleFullTitle: 'Kirin Ichiban 100% Malt',
    bottlePrice: '4.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'kirinichiban',
    bottleShortMaker: 'kirin-ichiban',
    bottleStock: 10,
    bottleShortName: 'kirin-ichiban-24oz',
    bottleImg: '/static/bottles/low-res/IMG_0952.png',
  },
  {
    bottleTitle: 'Sudwerk Brewing',
    bottleSubTitle: 'Bourbonator',
    bottleFullTitle: 'Sudwerk Brewing Bourbonator',
    bottlePrice: '6.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Sudwerk Brewing',
    bottleShortMaker: 'sudwerk-brewing',
    bottleStock: 10,
    bottleShortName: 'sudwerk-brewing-bourbonator',
    bottleImg: '/static/bottles/low-res/IMG_0954.jpg',
  },
  {
    bottleTitle: 'Port Brewing Co.',
    bottleSubTitle: 'Wipeout IPA',
    bottleFullTitle: 'Port Brewing Co. Wipeout IPA',
    bottlePrice: '6.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Port Brewing Co.',
    bottleShortMaker: 'port-brewing',
    bottleStock: 10,
    bottleShortName: 'port-brewing-wipeout',
    bottleImg: '/static/bottles/low-res/IMG_0956.jpg',
  },
  {
    bottleTitle: 'Lagunitas',
    bottleSubTitle: 'Maximus',
    bottleFullTitle: 'Lagunitas Maximus',
    bottlePrice: '6.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Lagunitas',
    bottleShortMaker: 'lagunitas',
    bottleStock: 10,
    bottleShortName: 'lagunitas-maximus',
    bottleImg: '/static/bottles/low-res/IMG_0959.jpg',
  },
  {
    bottleTitle: 'Dust Bowl',
    bottleSubTitle: 'Therapist Imperial IPA',
    bottleFullTitle: 'Dust Bowl Therapist Imperial IPA',
    bottlePrice: '6.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Dust Bowl',
    bottleShortMaker: 'dust-bowl',
    bottleStock: 10,
    bottleShortName: 'dust-bowl-imperial',
    bottleImg: '/static/bottles/low-res/IMG_0963.jpg',
  },
  {
    bottleTitle: 'Lagunitas',
    bottleSubTitle: 'Gnarly Wine',
    bottleFullTitle: 'Lagunitas Gnarly Wine',
    bottlePrice: '6.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Lagunitas',
    bottleShortMaker: 'lagunitas',
    bottleStock: 10,
    bottleShortName: 'lagunitas-gnarly-wine-24oz',
    bottleImg: '/static/bottles/low-res/IMG_0965.jpg',
  },
  {
    bottleTitle: 'Coedo',
    bottleSubTitle: 'Ruri',
    bottleFullTitle: 'Coedo Ruri',
    bottlePrice: '9.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Coedo',
    bottleShortMaker: 'coedo',
    bottleStock: 10,
    bottleShortName: 'coedo-ruri',
    bottleImg: '/static/bottles/low-res/IMG_0968.jpg',
  },
  {
    bottleTitle: 'Coedo',
    bottleSubTitle: 'Shikkoku',
    bottleFullTitle: 'Coedo Shikkoku',
    bottlePrice: '9.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Coedo',
    bottleShortMaker: 'coedo',
    bottleStock: 10,
    bottleShortName: 'coedo-shikkoku',
    bottleImg: '/static/bottles/low-res/IMG_0970.jpg',
  },
  {
    bottleTitle: 'Coedo',
    bottleSubTitle: 'Beniaka',
    bottleFullTitle: 'Coedo Beniaka',
    bottlePrice: '9.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Coedo',
    bottleShortMaker: 'coedo',
    bottleStock: 10,
    bottleShortName: 'coedo-beniaka',
    bottleImg: '/static/bottles/low-res/IMG_0972.jpg',
  },
  {
    bottleTitle: 'Coedo',
    bottleSubTitle: 'Shiro',
    bottleFullTitle: 'Coedo Shiro',
    bottlePrice: '9.99',
    bottleCategory: 'crafts',
    bottleSubCategory: 'tallbottles',
    bottleMaker: 'Coedo',
    bottleShortMaker: 'coedo',
    bottleStock: 10,
    bottleShortName: 'coedo-shiro',
    bottleImg: '/static/bottles/low-res/IMG_0974.jpg',
  },
  {
    bottleTitle: 'Hard Frescoes Brewing Co.',
    bottleSubTitle: 'Guava Citrico',
    bottleFullTitle: 'Hard Frescoes Brewing Co. Guava Citrico',
    bottlePrice: '10.99',
    bottleCategory: 'crafts',
    bottleSubCategory: '6packs',
    bottleMaker: 'Hard Frescoes Brewing Co.',
    bottleShortMaker: 'hard-frescoes',
    bottleStock: 10,
    bottleShortName: 'hard-frescoes-guava',
    bottleImg: '/static/bottles/low-res/IMG_1011.jpg',
  },
  {
    bottleTitle: 'Golden State',
    bottleSubTitle: 'Golden State Cider',
    bottleFullTitle: 'Cider',
    bottlePrice: '9.99',
    bottleCategory: 'crafts',
    bottleSubCategory: '6packs',
    bottleMaker: 'Golden State',
    bottleShortMaker: 'golden-state',
    bottleStock: 10,
    bottleShortName: 'golden-state-cider',
    bottleImg: '/static/bottles/low-res/IMG_1014.jpg',
  },
  {
    bottleTitle: 'Ménage à Trois',
    bottleSubTitle: 'California Red Wine',
    bottleFullTitle: 'Ménage à Trois California Red Wine',
    bottlePrice: '10.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Ménage à Trois',
    bottleShortMaker: 'menage-a-trois',
    bottleStock: 10,
    bottleShortName: 'menage-a-trois-california-red-wine',
    bottleImg: '/static/bottles/low-res/IMG_1095.jpg',
  },
  {
    bottleTitle: 'Mark West',
    bottleSubTitle: 'Black',
    bottleFullTitle: 'Mark West Black',
    bottlePrice: '15.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Mark West',
    bottleShortMaker: 'mark-west',
    bottleStock: 10,
    bottleShortName: 'mark-west-black',
    bottleImg: '/static/bottles/low-res/IMG_1097.jpg',
  },
  {
    bottleTitle: 'Toasted Head',
    bottleSubTitle: 'Cabernet Sauvignon',
    bottleFullTitle: 'Toasted Head Cabernet Sauvignon',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'cabs',
    bottleMaker: 'Toasted Head',
    bottleShortMaker: 'toasted-head',
    bottleStock: 10,
    bottleShortName: 'toasted-head-cabernet-sauvignon',
    bottleImg: '/static/bottles/low-res/IMG_1099.jpg',
  },
  {
    bottleTitle: 'Fetzer',
    bottleSubTitle: 'Monterey County Gewurztraminer',
    bottleFullTitle: 'Fetzer Monterey County Gewurztraminer',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'cabs',
    bottleMaker: 'Fetzer',
    bottleShortMaker: 'fetzer',
    bottleStock: 10,
    bottleShortName: 'fetzer-monterey-county-gwurztraminer',
    bottleImg: '/static/bottles/low-res/IMG_1101.jpg',
  },
  {
    bottleTitle: 'Ménage à Trois',
    bottleSubTitle: 'Midnight',
    bottleFullTitle: 'Ménage à Trois Midnight',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Ménage à Trois',
    bottleShortMaker: 'menage-a-trois',
    bottleStock: 10,
    bottleShortName: 'menage-a-trois-midnight',
    bottleImg: '/static/bottles/low-res/IMG_1103.jpg',
  },
  {
    bottleTitle: 'Mark West',
    bottleSubTitle: 'Pinot Noir 2014',
    bottleFullTitle: 'Mark West Pinot Noir 2014',
    bottlePrice: '19.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'pinot-noir',
    bottleMaker: 'Mark West',
    bottleShortMaker: 'mark-west',
    bottleStock: 10,
    bottleShortName: 'mark-west-pinot-noir-2014',
    bottleImg: '/static/bottles/low-res/IMG_1106.jpg',
  },
  {
    bottleTitle: 'Alma Mora',
    bottleSubTitle: 'Red Blend',
    bottleFullTitle: 'Alma Mora RedBlend',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Alma Mora',
    bottleShortMaker: 'alma-mora',
    bottleStock: 10,
    bottleShortName: 'alma-mora-red-blend',
    bottleImg: '/static/bottles/low-res/IMG_1107.jpg',
  },
  {
    bottleTitle: 'Bogle Vineyards',
    bottleSubTitle: 'Essential Red 2015',
    bottleFullTitle: 'Bogle Vineyards Essential Red 2015',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Bogle Vineyards',
    bottleShortMaker: 'bogle-vineyards',
    bottleStock: 10,
    bottleShortName: 'bogle-vineyards-red-2015',
    bottleImg: '/static/bottles/low-res/IMG_1108.jpg',
  },
  {
    bottleTitle: 'Ménage à Trois',
    bottleSubTitle: 'Silk',
    bottleFullTitle: 'Ménage à Trois Silk',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Ménage à Trois',
    bottleShortMaker: 'menage-a-trois',
    bottleStock: 10,
    bottleShortName: 'menage-a-trois-silk',
    bottleImg: '/static/bottles/low-res/IMG_1111.jpg',
  },
  {
    bottleTitle: 'White Girl',
    bottleSubTitle: 'Rosé',
    bottleFullTitle: 'White Girl Rosé',
    bottlePrice: '14.99',
    bottleCategory: 'specialty',
    bottleSubCategory: '',
    bottleMaker: 'champagne',
    bottleShortMaker: 'white-girl',
    bottleStock: 10,
    bottleShortName: 'white-girl-rose',
    bottleImg: '/static/bottles/low-res/IMG_1112.jpg',
  },
  {
    bottleTitle: 'Apothic',
    bottleSubTitle: 'Red',
    bottleFullTitle: 'Apothic Red',
    bottlePrice: '9.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'reds',
    bottleMaker: 'Apothic',
    bottleShortMaker: 'apothic',
    bottleStock: 10,
    bottleShortName: 'apothic-red',
    bottleImg: '/static/bottles/low-res/IMG_1114.jpg',
  },
  {
    bottleTitle: 'Zombie Zin',
    bottleSubTitle: 'California Zinfandel',
    bottleFullTitle: 'Zombie Zin California Zinfandel',
    bottlePrice: '14.99',
    bottleCategory: 'wines',
    bottleSubCategory: 'zinfandel',
    bottleMaker: 'Zombie',
    bottleShortMaker: 'zombie',
    bottleStock: 10,
    bottleShortName: 'zombie-zin',
    bottleImg: '/static/bottles/low-res/IMG_1136.jpg',
  },
  {
    bottleTitle: 'Glacier',
    bottleSubTitle: 'Smart Water',
    bottleFullTitle: 'Glacier Smart Water',
    bottlePrice: '1.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'water',
    bottleMaker: 'Glacier',
    bottleShortMaker: 'glacier',
    bottleStock: 10,
    bottleShortName: 'glacier-smart-water',
    bottleImg: '/static/bottles/low-res/IMG_1142.jpg',
  },
  {
    bottleTitle: 'Glacier',
    bottleSubTitle: 'Smart Water',
    bottleFullTitle: 'Glacier Smart Water',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'water',
    bottleMaker: 'Glacier',
    bottleShortMaker: 'glacier',
    bottleStock: 10,
    bottleShortName: 'glacier-smart-water',
    bottleImg: '/static/bottles/low-res/IMG_1145.jpg',
  },
  {
    bottleTitle: 'Fiji',
    bottleSubTitle: 'Artisinal Water',
    bottleFullTitle: 'Fiji Artisinal Water',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'water',
    bottleMaker: 'fiji',
    bottleShortMaker: 'fiji',
    bottleStock: 10,
    bottleShortName: 'fiji-artisinal-water',
    bottleImg: '/static/bottles/low-res/IMG_1147.jpg',
  }
]

export default bottles
