const shoppingCart = [
  {
    bottleTitle: 'Hangar 1',
    bottleSubTitle: 'Straight Vodka',
    bottleFullTitle: 'Hangar 1 Straight Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Hangar 1',
    bottleShortMaker: 'hangar1',
    bottleStock: 10,
    bottleShortName: 'hangar1-straightvodka',
    bottleImg: '/static/bottles/bottle_6.png',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'All Purpose Vodka',
    bottleFullTitle: 'St. George All Purpose Vodka',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-allpurpose',
    bottleImg: '/static/bottles/bottle_8.png',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'Single Malt Whiskey',
    bottleFullTitle: 'St. George Single Malt Whiskey',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-singlemaltwhiskey',
    bottleImg: '/static/bottles/bottle_5.png',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Blanc',
    bottleFullTitle: 'Dolin Vermouth Blanc',
    bottlePrice: '29.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-blanc',
    bottleImg: '/static/bottles/bottle_9.png',
  },

  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Rouge',
    bottleFullTitle: 'Dolin Vermouth Rouge',
    bottlePrice: '29.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-rouge',
    bottleImg: '/static/bottles/bottle_7.png',
  },
]

export default shoppingCart
