const bottles = [
  {
    bottleTitle: 'Hangar 1',
    bottleSubTitle: 'Straight Vodka',
    bottleFullTitle: 'Hangar 1 Straight Vodka',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Hangar 1',
    bottleShortMaker: 'hangar1',
    bottleStock: 10,
    bottleShortName: 'hangar1-straightvodka',
    bottleImg: '/static/bottles/low-res/Hangar1-straight.png',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'All Purpose Vodka',
    bottleFullTitle: 'St. George All Purpose Vodka',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-allpurpose',
    bottleImg: '/static/bottles/low-res/StGeorge-all-purpose.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'Single Malt Whiskey',
    bottleFullTitle: 'St. George Single Malt Whiskey',
    bottlePrice: '39.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-singlemaltwhiskey',
    bottleImg: '/static/bottles/low-res/StGeorge-whiskey.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'California Citrus',
    bottleFullTitle: 'St. George California Citrus',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-cc',
    bottleImg: '/static/bottles/low-res/StGeorge_cacitrus.jpg',
  },
  {
    bottleTitle: 'St. George',
    bottleSubTitle: 'Green Chile',
    bottleFullTitle: 'St. George Green Chile',
    bottlePrice: '34.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'St. George',
    bottleShortMaker: 'stgeorge',
    bottleStock: 10,
    bottleShortName: 'stgeorge-green-chile',
    bottleImg: '/static/bottles/low-res/StGeorge_grnchile.jpg',
  },
  {
    bottleTitle: 'Bulliet',
    bottleSubTitle: 'Frontier Whiskey',
    bottleFullTitle: 'Bulliet Bourbon Frontier Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Bulliet Bourbon',
    bottleShortMaker: 'bulliet',
    bottleStock: 10,
    bottleShortName: 'bulliet-whiskey',
    bottleImg: '/static/bottles/low-res/Bulliet.jpg',
  },
  {
    bottleTitle: 'Bulliet',
    bottleSubTitle: 'Rye Whiskey',
    bottleFullTitle: 'Bulliet Bourbon Rye Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Bulliet Bourbon',
    bottleShortMaker: 'bulliet',
    bottleStock: 10,
    bottleShortName: 'bulliet-rye-whiskey',
    bottleImg: '/static/bottles/low-res/BullietRye.jpg',
  },
  {
    bottleTitle: 'Evan Williams',
    bottleSubTitle: 'Straight Bourbon Whiskey',
    bottleFullTitle: 'Evan Williams Straight Bourbon Whiskey',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Evan Williams',
    bottleShortMaker: 'evanwilliams',
    bottleStock: 10,
    bottleShortName: 'evanwilliams-straight-whiskey',
    bottleImg: '/static/bottles/low-res/EvanWilliams.jpg',
  },
  {
    bottleTitle: 'Fireball',
    bottleSubTitle: 'Cinnamon Whiskey',
    bottleFullTitle: 'Fireball Cinnamon Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Fireball',
    bottleShortMaker: 'fireball',
    bottleStock: 10,
    bottleShortName: 'fireball-cinnamon-whiskey',
    bottleImg: '/static/bottles/low-res/Fireball.jpg',
  },
  {
    bottleTitle: 'Iwai',
    bottleSubTitle: 'Mars Whiskey',
    bottleFullTitle: 'Iwai Mars Whiskey',
    bottlePrice: '109.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Iwai',
    bottleShortMaker: 'iwai',
    bottleStock: 10,
    bottleShortName: 'iwai-mars-whiskey',
    bottleImg: '/static/bottles/low-res/Iwai.jpg',
  },
  {
    bottleTitle: 'Iwai',
    bottleSubTitle: 'Tradition Whiskey',
    bottleFullTitle: 'Iwai Tradition Whiskey',
    bottlePrice: '109.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Iwai',
    bottleShortMaker: 'iwai',
    bottleStock: 10,
    bottleShortName: 'iwai-tradition-whiskey',
    bottleImg: '/static/bottles/low-res/Iwai_tradition.jpg',
  },
  {
    bottleTitle: 'Jameson',
    bottleSubTitle: 'Irish Whiskey',
    bottleFullTitle: 'Jameson Irish Whiskey',
    bottlePrice: '36.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Jameson',
    bottleShortMaker: 'jameson',
    bottleStock: 10,
    bottleShortName: 'jameson-irish-whiskey',
    bottleImg: '/static/bottles/low-res/Jameson_15.jpg',
  },
  {
    bottleTitle: 'Jameson',
    bottleSubTitle: 'Irish Whiskey',
    bottleFullTitle: 'Jameson Irish Whiskey',
    bottlePrice: '24.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'whiskey',
    bottleMaker: 'Jameson',
    bottleShortMaker: 'jameson',
    bottleStock: 10,
    bottleShortName: 'jameson-irish-whiskey',
    bottleImg: '/static/bottles/low-res/Jameson_750ml.jpg',
  },
  {
    bottleTitle: 'Centenario',
    bottleSubTitle: 'Anejo',
    bottleFullTitle: 'Centenario Anejo',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Centenario',
    bottleShortMaker: 'centenario',
    bottleStock: 10,
    bottleShortName: 'centenario-anejo',
    bottleImg: '/static/bottles/low-res/Centario.jpg',
  },
  {
    bottleTitle: 'Suerte',
    bottleSubTitle: 'Blanco',
    bottleFullTitle: 'Suerte Blanco',
    bottlePrice: '22.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Suerte',
    bottleShortMaker: 'suerte',
    bottleStock: 10,
    bottleShortName: 'suerte-blanco',
    bottleImg: '/static/bottles/low-res/Suerte.jpg',
  },
  {
    bottleTitle: 'Nuestra Soledad',
    bottleSubTitle: 'Mezcal',
    bottleFullTitle: 'Nuestra Soledad Mezcal',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'tequila',
    bottleMaker: 'Nuestra Soledad',
    bottleShortMaker: 'nuestra-soledad',
    bottleStock: 10,
    bottleShortName: 'nuestra-soledad-mezcal',
    bottleImg: '/static/bottles/low-res/Nuestra_soledad.jpg',
  },
  {
    bottleTitle: 'Effen',
    bottleSubTitle: 'Vodka',
    bottleFullTitle: 'Effen Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Effen',
    bottleShortMaker: 'effen',
    bottleStock: 10,
    bottleShortName: 'effen-vodka',
    bottleImg: '/static/bottles/low-res/Effen_clr.jpg',
  },
  {
    bottleTitle: 'Skyy',
    bottleSubTitle: 'Vodka',
    bottleFullTitle: 'Skyy Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Skyy',
    bottleShortMaker: 'skyy',
    bottleStock: 10,
    bottleShortName: 'skyy-vodka',
    bottleImg: '/static/bottles/low-res/Skyy.jpg',
  },
  {
    bottleTitle: 'Tito\'s',
    bottleSubTitle: 'Handmade Vodka',
    bottleFullTitle: 'Tito\'s Handmade Vodka',
    bottlePrice: '29.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Tito\'s',
    bottleShortMaker: 'titos',
    bottleStock: 10,
    bottleShortName: 'titos-handmade-vodka',
    bottleImg: '/static/bottles/low-res/Titos.jpg',
  },
  {
    bottleTitle: 'Effen',
    bottleSubTitle: 'Cucumber Vodka',
    bottleFullTitle: 'Effen Cucumber Vodka',
    bottlePrice: '19.99',
    bottleCategory: 'spirits',
    bottleSubCategory: 'vodka',
    bottleMaker: 'Effen',
    bottleShortMaker: 'effen',
    bottleStock: 10,
    bottleShortName: 'effen-cucumber-vodka',
    bottleImg: '/static/bottles/low-res/Effen_grn.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Blanc',
    bottleFullTitle: 'Dolin Vermouth Blanc',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-blanc',
    bottleImg: '/static/bottles/low-res/Dolin-vermouth-blanc.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Rouge',
    bottleFullTitle: 'Dolin Vermouth Rouge',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-rouge',
    bottleImg: '/static/bottles/low-res/Dolin-rouge.jpg',
  },
  {
    bottleTitle: 'Dolin',
    bottleSubTitle: 'Vermouth Dry',
    bottleFullTitle: 'Dolin Vermouth Dry',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Dolin',
    bottleShortMaker: 'dolin',
    bottleStock: 10,
    bottleShortName: 'dolin-vermouth-dry',
    bottleImg: '/static/bottles/low-res/Dolin_vermouthdry.jpg',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Dry Vermouth',
    bottleFullTitle: 'Lo-fi Dry Vermouth',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-dry-vermouth',
    bottleImg: '/static/bottles/low-res/Lofi-dry-vermouth.jpg',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Gentian Amaro',
    bottleFullTitle: 'Lo-fi Gentian Amaro',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-gentian-amaro',
    bottleImg: '/static/bottles/low-res/Lofi-gentian-amaro.png',
  },
  {
    bottleTitle: 'Lo-fi',
    bottleSubTitle: 'Sweet Vermouth',
    bottleFullTitle: 'Lo-fi Sweet Vermouth',
    bottlePrice: '19.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'vermouth',
    bottleMaker: 'Lo-fi',
    bottleShortMaker: 'lofi',
    bottleStock: 10,
    bottleShortName: 'lofi-sweet-vermouth',
    bottleImg: '/static/bottles/low-res/Lofi-sweet-vermouth.jpg',
  },
  {
    bottleTitle: 'Moet & Chandon',
    bottleSubTitle: 'Nectar Imperial',
    bottleFullTitle: 'Moet & Chandon Nectar Imperial',
    bottlePrice: '69.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'champagne',
    bottleMaker: 'Moet & Chandon',
    bottleShortMaker: 'moet-chandon',
    bottleStock: 10,
    bottleShortName: 'moet-chandon-nectar-imperial',
    bottleImg: '/static/bottles/low-res/MC_nectarimperial.jpg',
  },
  {
    bottleTitle: 'Perrier Jouet',
    bottleSubTitle: 'Blanc',
    bottleFullTitle: 'Perrier Joet Blanc',
    bottlePrice: '399.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'champagne',
    bottleMaker: 'Perrier Jouet',
    bottleShortMaker: 'perrier-jouet',
    bottleStock: 10,
    bottleShortName: 'perrier-jouet-blanc',
    bottleImg: '/static/bottles/low-res/PJ_blanc.jpg',
  },
  {
    bottleTitle: 'Fever-Tree',
    bottleSubTitle: 'Club Soda',
    bottleFullTitle: 'Fever-Tree Club Soda',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Fever-Tree',
    bottleShortMaker: 'fevertree',
    bottleStock: 10,
    bottleShortName: 'fevertree-clubsoda',
    bottleImg: '/static/bottles/low-res/FT_Clubsoda.jpg',
  },
  {
    bottleTitle: 'Fever-Tree',
    bottleSubTitle: 'Tonic Water',
    bottleFullTitle: 'Fever-Tree Tonic Water',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Fever-Tree',
    bottleShortMaker: 'fevertree',
    bottleStock: 10,
    bottleShortName: 'fevertree-tonicwater',
    bottleImg: '/static/bottles/low-res/FT_Tonicwater.jpg',
  },
  {
    bottleTitle: 'Martinelli\'s',
    bottleSubTitle: 'Apple Juice',
    bottleFullTitle: 'Martinelli\'s Apple Juice',
    bottlePrice: '3.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Martinelli\'s',
    bottleShortMaker: 'martinellis',
    bottleStock: 10,
    bottleShortName: 'martinellis-applejuice',
    bottleImg: '/static/bottles/low-res/Martin_Apple.jpg',
  },
  {
    bottleTitle: 'Bundaberg',
    bottleSubTitle: 'Pink Grapefruit',
    bottleFullTitle: 'Bundaberg Pink Grapefruit',
    bottlePrice: '6.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Bundaberg',
    bottleShortMaker: 'bundaberg',
    bottleStock: 10,
    bottleShortName: 'bundaberg-pinkgrapefruit-pck',
    bottleImg: '/static/bottles/low-res/Bundaberg.jpg',
  },
  {
    bottleTitle: 'Canada Dry',
    bottleSubTitle: 'Mandarin Orange',
    bottleFullTitle: 'Canada Dry Mandarin Orange',
    bottlePrice: '2.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Canada Dry',
    bottleShortMaker: 'canadadry',
    bottleStock: 10,
    bottleShortName: 'canadadry-mandarinorange',
    bottleImg: '/static/bottles/low-res/CD_Mandarinsprk.jpg',
  },
  {
    bottleTitle: 'Canada Dry',
    bottleSubTitle: 'Raspberry',
    bottleFullTitle: 'Canada Dry Raspberry',
    bottlePrice: '2.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'soda',
    bottleMaker: 'Canada Dry',
    bottleShortMaker: 'canadadry',
    bottleStock: 10,
    bottleShortName: 'canadadry-raspberry',
    bottleImg: '/static/bottles/low-res/CD_Raspberrysprk.jpg',
  },
  {
    bottleTitle: 'Clandestine',
    bottleSubTitle: 'Absinthe',
    bottleFullTitle: 'Clandestine Absinthe',
    bottlePrice: '69.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'absinthe',
    bottleMaker: 'Clandestine',
    bottleShortMaker: 'clandestine',
    bottleStock: 10,
    bottleShortName: 'clandestine-absinthe',
    bottleImg: '/static/bottles/low-res/Clandestine_absinthe.jpg',
  },
  {
    bottleTitle: 'Fernet Branca',
    bottleSubTitle: 'Liqueur',
    bottleFullTitle: 'Fernet Branca Liqueur',
    bottlePrice: '34.99',
    bottleCategory: 'specialty',
    bottleSubCategory: 'liqueur',
    bottleMaker: 'Fernet Branca',
    bottleShortMaker: 'fernet-branca',
    bottleStock: 10,
    bottleShortName: 'fernet-branca-liqueur',
    bottleImg: '/static/bottles/low-res/Fernet_branca.jpg',
  },
  {
    bottleTitle: 'Masters of Mixers',
    bottleSubTitle: 'Unsweeted Lemon Juice',
    bottleFullTitle: 'Masters of Mixers Unsweeted Lemon Juice',
    bottlePrice: '4.99',
    bottleCategory: 'misc',
    bottleSubCategory: 'mixers',
    bottleMaker: 'Masters of Mixers',
    bottleShortMaker: 'masters-mixers',
    bottleStock: 10,
    bottleShortName: 'masters-mixers-unsweeted-lemon-juice',
    bottleImg: '/static/bottles/low-res/MM_Lemonjuice.jpg',
  }
]

export default bottles
